version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile
  slack: circleci/slack@4.9.3

commands:
  notify:
      steps:
        - slack/notify:
            event: fail
            template: basic_fail_1
            branch_pattern: master

jobs:
  run-specs-with-postgres:
    executor: solidusio_extensions/postgres
    steps:
      - solidusio_extensions/run-tests
      - notify
  run-specs-with-mysql:
    executor: solidusio_extensions/mysql
    steps:
      - solidusio_extensions/run-tests
      - notify

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-postgres:
          context: slack-secrets
      - run-specs-with-mysql:
          context: slack-secrets
  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-with-postgres:
          context: slack-secrets
      - run-specs-with-mysql:
          context: slack-secrets
